-- MySQL Script generated by MySQL Workbench
-- Thu Mar 16 00:50:01 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `username` VARCHAR(255) NULL,
  `auth_key` VARCHAR(32) NULL,
  `password_hash` VARCHAR(255) NULL,
  `password_reset_token` VARCHAR(255) NULL,
  `age` INT(5) NULL,
  `phone_number` INT(11) NULL,
  `email` VARCHAR(255) NULL,
  `status` SMALLINT(6) NULL,
  `created_at` INT(11) NULL,
  `updated_at` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `id` INT NOT NULL,
  `username` VARCHAR(255) NULL,
  `auth_key` VARCHAR(32) NULL,
  `password_hash` VARCHAR(255) NULL,
  `password_reset_token` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `status` SMALLINT(6) NULL,
  `created_at` INT(11) NULL,
  `updated_at` INT(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`post` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `admin_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `admin_id`),
  INDEX `fk_post_user_idx` (`user_id` ASC),
  INDEX `fk_post_admin1_idx` (`admin_id` ASC),
  CONSTRAINT `fk_post_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_admin1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `mydb`.`admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`missing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`missing` (
  `id` INT NOT NULL,
  `post_id` INT NOT NULL,
  `post_user_id` INT NOT NULL,
  `submission_id` VARCHAR(255) NULL,
  `photo` LONGBLOB NULL,
  `first_name` VARCHAR(45) NULL,
  `middle_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `address` VARCHAR(100) NULL,
  `marital_status` VARCHAR(45) NULL,
  `sex` VARCHAR(45) NULL,
  `birthdate` VARCHAR(45) NULL,
  `age` VARCHAR(45) NULL,
  `occupation` VARCHAR(45) NULL,
  `date_of_disappearance` VARCHAR(45) NULL,
  `time_of_disappearance` VARCHAR(45) NULL,
  `last_seen` VARCHAR(255) NULL,
  `relationship_with_person` VARCHAR(45) NULL,
  `height` VARCHAR(45) NULL,
  `weight` VARCHAR(45) NULL,
  `eye_color` VARCHAR(45) NULL,
  `hair_length` VARCHAR(45) NULL,
  `hair_color` VARCHAR(45) NULL,
  `facial_hair` VARCHAR(45) NULL,
  `facial_hair_color` VARCHAR(45) NULL,
  `facial_hair_length` VARCHAR(45) NULL,
  `ear_shape` VARCHAR(45) NULL,
  `eyebrows_size` VARCHAR(45) NULL,
  `nose_size` VARCHAR(45) NULL,
  `hand_size` VARCHAR(45) NULL,
  `feet_size` VARCHAR(45) NULL,
  `distinguishing_features` VARCHAR(45) NULL,
  `scar_location` VARCHAR(255) NULL,
  `tattoo_location` VARCHAR(255) NULL,
  `birthmark_location` VARCHAR(255) NULL,
  `mole_location` VARCHAR(255) NULL,
  `upper_garment` VARCHAR(45) NULL,
  `upper_garment_color` VARCHAR(45) NULL,
  `lower_garment` VARCHAR(45) NULL,
  `lower_garment_color` VARCHAR(45) NULL,
  `footwear` VARCHAR(45) NULL,
  `eyewear` VARCHAR(45) NULL,
  `glasses_color` VARCHAR(45) NULL,
  `contact_lens_color` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `post_id`, `post_user_id`),
  INDEX `fk_missing_post1_idx` (`post_id` ASC, `post_user_id` ASC),
  CONSTRAINT `fk_missing_post1`
    FOREIGN KEY (`post_id` , `post_user_id`)
    REFERENCES `mydb`.`post` (`id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dead`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dead` (
  `id` INT NOT NULL,
  `post_id` INT NOT NULL,
  `post_user_id` INT NOT NULL,
  `submission_id` VARCHAR(255) NULL,
  `general_condition` VARCHAR(45) NULL,
  `body_part_found` VARCHAR(45) NULL,
  `body_condition` VARCHAR(45) NULL,
  `apparent_sex` VARCHAR(45) NULL,
  `age_group` VARCHAR(45) NULL,
  `height` VARCHAR(45) NULL,
  `weight` VARCHAR(45) NULL,
  `hair_length` VARCHAR(45) NULL,
  `hair_color` VARCHAR(45) NULL,
  `facial_hair_type` VARCHAR(45) NULL,
  `facial_hair_length` VARCHAR(45) NULL,
  `facial_hair_color` VARCHAR(45) NULL,
  `distinguishing_features` VARCHAR(45) NULL,
  `scar_location` VARCHAR(255) NULL,
  `tattoo_location` VARCHAR(255) NULL,
  `birthmark_location` VARCHAR(255) NULL,
  `mole_location` VARCHAR(255) NULL,
  `upper_garment` VARCHAR(45) NULL,
  `upper_garment_color` VARCHAR(45) NULL,
  `lower_garment` VARCHAR(45) NULL,
  `lower_garment_color` VARCHAR(45) NULL,
  `footwear` VARCHAR(45) NULL,
  `eyewear` VARCHAR(45) NULL,
  `galsses_color` VARCHAR(45) NULL,
  `contact_lens_color` VARCHAR(45) NULL,
  `photo` LONGBLOB NULL,
  PRIMARY KEY (`id`, `post_id`, `post_user_id`),
  INDEX `fk_dead_post1_idx` (`post_id` ASC, `post_user_id` ASC),
  CONSTRAINT `fk_dead_post1`
    FOREIGN KEY (`post_id` , `post_user_id`)
    REFERENCES `mydb`.`post` (`id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`volunteer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`volunteer` (
  `id` INT NOT NULL,
  `address` VARCHAR(255) NULL,
  `volunteer_experience` VARCHAR(45) NULL,
  `occupation` VARCHAR(45) NULL,
  `educational_attainment` VARCHAR(45) NULL,
  `availability` VARCHAR(255) NULL,
  `serve_more_than_one` VARCHAR(45) NULL,
  `driver_license` VARCHAR(45) NULL,
  `convicted` VARCHAR(45) NULL,
  `conviction_reason` VARCHAR(255) NULL,
  `physical_limitation` VARCHAR(45) NULL,
  `limitation_description` VARCHAR(255) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_volunteer_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_volunteer_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`references`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`references` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `relationship_with_person` VARCHAR(45) NULL,
  `phone_number` VARCHAR(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`volunteer_has_references`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`volunteer_has_references` (
  `volunteer_user_id` INT NOT NULL,
  `references_id` INT NOT NULL,
  PRIMARY KEY (`volunteer_user_id`, `references_id`),
  INDEX `fk_volunteer_has_references_references1_idx` (`references_id` ASC),
  INDEX `fk_volunteer_has_references_volunteer1_idx` (`volunteer_user_id` ASC),
  CONSTRAINT `fk_volunteer_has_references_volunteer1`
    FOREIGN KEY (`volunteer_user_id`)
    REFERENCES `mydb`.`volunteer` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_volunteer_has_references_references1`
    FOREIGN KEY (`references_id`)
    REFERENCES `mydb`.`references` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`emergency_contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`emergency_contacts` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `relationship_with_person` VARCHAR(45) NULL,
  `phone_number` VARCHAR(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`volunteer_has_emergency_contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`volunteer_has_emergency_contacts` (
  `volunteer_user_id` INT NOT NULL,
  `emergency_contacts_id` INT NOT NULL,
  PRIMARY KEY (`volunteer_user_id`, `emergency_contacts_id`),
  INDEX `fk_volunteer_has_emergency_contacts_emergency_contacts1_idx` (`emergency_contacts_id` ASC),
  INDEX `fk_volunteer_has_emergency_contacts_volunteer1_idx` (`volunteer_user_id` ASC),
  CONSTRAINT `fk_volunteer_has_emergency_contacts_volunteer1`
    FOREIGN KEY (`volunteer_user_id`)
    REFERENCES `mydb`.`volunteer` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_volunteer_has_emergency_contacts_emergency_contacts1`
    FOREIGN KEY (`emergency_contacts_id`)
    REFERENCES `mydb`.`emergency_contacts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
