-- MySQL Script generated by MySQL Workbench
-- Wed Mar 29 13:37:33 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `middle_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `username` VARCHAR(255) NULL,
  `gender` VARCHAR(45) NULL,
  `birthday` VARCHAR(45) NULL,
  `age` INT NULL,
  `phone_number` INT NULL,
  `address` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `auth_key` VARCHAR(32) NULL,
  `password_hash` VARCHAR(255) NULL,
  `password_reset_token` VARCHAR(255) NULL,
  `status` SMALLINT(6) NULL,
  `created_at` INT(11) NULL,
  `updated_at` INT(11) NULL,
  `user_type` ENUM('regular', 'admin', 'volunteer') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`missing_people`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`missing_people` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `submission_id` VARCHAR(255) NULL,
  `photo` LONGBLOB NULL,
  `first_name` VARCHAR(45) NULL,
  `middle_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `address` VARCHAR(100) NULL,
  `marital_status` VARCHAR(45) NULL,
  `sex` VARCHAR(45) NULL,
  `birthdate` VARCHAR(45) NULL,
  `age` VARCHAR(45) NULL,
  `occupation` VARCHAR(45) NULL,
  `date_of_disappearance` VARCHAR(45) NULL,
  `time_of_disappearance` VARCHAR(45) NULL,
  `last_seen` VARCHAR(255) NULL,
  `relationship_with_person` VARCHAR(45) NULL,
  `height` VARCHAR(45) NULL,
  `weight` VARCHAR(45) NULL,
  `eye_color` VARCHAR(45) NULL,
  `hair_length` VARCHAR(45) NULL,
  `hair_color` VARCHAR(45) NULL,
  `facial_hair` VARCHAR(45) NULL,
  `facial_hair_color` VARCHAR(45) NULL,
  `facial_hair_length` VARCHAR(45) NULL,
  `ear_shape` VARCHAR(45) NULL,
  `eyebrows_size` VARCHAR(45) NULL,
  `nose_size` VARCHAR(45) NULL,
  `hand_size` VARCHAR(45) NULL,
  `feet_size` VARCHAR(45) NULL,
  `distinguishing_features` VARCHAR(45) NULL,
  `scar_location` VARCHAR(255) NULL,
  `tattoo_location` VARCHAR(255) NULL,
  `birthmark_location` VARCHAR(255) NULL,
  `mole_location` VARCHAR(255) NULL,
  `upper_garment` VARCHAR(45) NULL,
  `upper_garment_color` VARCHAR(45) NULL,
  `lower_garment` VARCHAR(45) NULL,
  `lower_garment_color` VARCHAR(45) NULL,
  `footwear` VARCHAR(45) NULL,
  `eyewear` VARCHAR(45) NULL,
  `glasses_color` VARCHAR(45) NULL,
  `contact_lens_color` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_missing_people_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_missing_people_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dead_people`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dead_people` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `submission_id` VARCHAR(255) NULL,
  `general_condition` VARCHAR(45) NULL,
  `body_part_found` VARCHAR(45) NULL,
  `body_condition` VARCHAR(45) NULL,
  `apparent_sex` VARCHAR(45) NULL,
  `age_group` VARCHAR(45) NULL,
  `height` VARCHAR(45) NULL,
  `weight` VARCHAR(45) NULL,
  `hair_length` VARCHAR(45) NULL,
  `hair_color` VARCHAR(45) NULL,
  `facial_hair_type` VARCHAR(45) NULL,
  `facial_hair_length` VARCHAR(45) NULL,
  `facial_hair_color` VARCHAR(45) NULL,
  `distinguishing_features` VARCHAR(45) NULL,
  `scar_location` VARCHAR(255) NULL,
  `tattoo_location` VARCHAR(255) NULL,
  `birthmark_location` VARCHAR(255) NULL,
  `mole_location` VARCHAR(255) NULL,
  `upper_garment` VARCHAR(45) NULL,
  `upper_garment_color` VARCHAR(45) NULL,
  `lower_garment` VARCHAR(45) NULL,
  `lower_garment_color` VARCHAR(45) NULL,
  `footwear` VARCHAR(45) NULL,
  `eyewear` VARCHAR(45) NULL,
  `galsses_color` VARCHAR(45) NULL,
  `contact_lens_color` VARCHAR(45) NULL,
  `photo` LONGBLOB NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_dead_people_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_dead_people_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`volunteer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`volunteer` (
  `user_id` INT NOT NULL,
  `address` VARCHAR(255) NULL,
  `volunteer_experience` VARCHAR(45) NULL,
  `occupation` VARCHAR(45) NULL,
  `educational_attainment` VARCHAR(45) NULL,
  `availability` VARCHAR(255) NULL,
  `serve_more_than_one` VARCHAR(45) NULL,
  `driver_license` VARCHAR(45) NULL,
  `convicted` VARCHAR(45) NULL,
  `conviction_reason` VARCHAR(255) NULL,
  `physical_limitation` VARCHAR(45) NULL,
  `limitation_description` VARCHAR(255) NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_volunteer_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_volunteer_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`emergency_contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`emergency_contacts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `relationship_with_person` VARCHAR(45) NULL,
  `phone_number` VARCHAR(11) NULL,
  `volunteer_user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `volunteer_user_id`),
  INDEX `fk_emergency_contacts_volunteer1_idx` (`volunteer_user_id` ASC),
  CONSTRAINT `fk_emergency_contacts_volunteer1`
    FOREIGN KEY (`volunteer_user_id`)
    REFERENCES `mydb`.`volunteer` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
